### ISSUE TITLE
stop hoisting non-enumerables

### ISSUE THREAD

**Issue by nfcampos** [mridgway/hoist-non-react-statics#11]
Hi,

The original reason for having started to hoist non-enumerable properties was babel transpiling static class properties as non-enumerable. Babel no longer does that. Can this be changed back to hoist only enumerables, or can an option be added to hoist non-enumerables or not?
I'm willing to submit a PR changing this if it's welcome

(original change: https://github.com/mridgway/hoist-non-react-statics/pull/3)

Thanks,
Nuno

**Comment by mridgway** [comment]
Has the spec finalized on these being enumerable? I have a feeling that babel is just speculating on their behavior. I haven't been following this closely so if you have any links to the decision within babel that would be helpful.

**Comment by nfcampos** [comment]
yeah you're probably right, it's best to change this again only once the spec finalises.
though it'd be probably be better to mention in the README that this hoists non-enumerables, which is kind of unexpected.

**Comment by mridgway** [comment]
I am leaning towards moving in this direction to be more in line with `Object.assign` (the original goal). Looking at the current proposal, statics will be enumerable. Since this may be considered a breaking change, I will do this as a new major version.

**Comment by awitherow** [comment]
Any work on this @mridgway @nfcampos ? We are using your library now and would like to help solve things.

**Comment by mridgway** [comment]
I have not had time to work on this, but my thinking right now is to more directly emulate `object-assign`'s logic and release it as a major version since it may break some components. This would greatly simplify the logic and also more closely follow my original goal.
