### ISSUE TITLE
`isMemo` check always returns false for components

### ISSUE THREAD

**Issue by Harshit369** [mridgway/hoist-non-react-statics#118]
[React-is](https://www.npmjs.com/package/react-is) type check methods like `isFragment` `isMemo` are only applicable for element types as the readme says, not components.
>This package allows you to test arbitrary values and see if they're a particular **React element** type.

This LOC will always return false here: 
https://github.com/mridgway/hoist-non-react-statics/blob/master/src/index.js#L54

The `React-is` first checks if the passed param is at least an element else it doesn't check its type at all.

**Comment by eps1lon** [comment]
Check the comment above. This line is specifically for React 16.11 and below when react-is did work differently.

**Comment by Harshit369** [comment]
Missed that. Thanks for addressing 👏
Closing this.
