### ISSUE TITLE
Suggestion: Add explanation to README 

### ISSUE THREAD

**Issue by nwshane** [mridgway/hoist-non-react-statics#25]
I didn't understand what this library did at first, and I think it's a bit tricky for people who are new to React. Would it be worth adding a more detailed explanation of what the library does to the README? 

If others think this would be valuable, I can submit a PR with such an explanation.

**Comment by mridgway** [comment]
I can see that while it may be clear what it's doing, it may be unclear *why* this is needed. It's probably a good idea to add a "why" section to the readme with an example higher order component that illustrates the issue.

**Comment by nwshane** [comment]
Okay. I'll write a Why section up later and you can give me feedback on whether it's helpful or not.

**Comment by nwshane** [comment]
@menelike Ah, yeah that do the trick. Thanks for the link!

**Comment by mridgway** [comment]
Fixed in #26. Thanks for mentioning that @menelike.
