### ISSUE TITLE
Doesn't hoist static

### ISSUE THREAD

**Issue by pencilcheck** [mridgway/hoist-non-react-statics#29]
i'm on nextjs, this package doesn't hoist getInitialProps, which is a non react static method.

**Comment by pencilcheck** [comment]
Some reference: https://github.com/reactjs/redux/issues/181

**Comment by mridgway** [comment]
I am actively looking into this. I consider this a regression in 2.x. I will be adding support for static methods even if the spec and/or Babel does not make them enumerable.

**Comment by pencilcheck** [comment]
Thanks, confirmed that it works 👍
