### ISSUE TITLE
Crash in React Native

### ISSUE THREAD

**Issue by gaguirre** [mridgway/hoist-non-react-statics#32]
I'm getting the following error when using it in React Native (with Debug JS mode disabled)
It fails with version **2.1.0** but it works with **2.0.0** so downgrading is a workaround.

![screen shot 2017-07-12 at 12 08 21 pm](https://user-images.githubusercontent.com/1652196/28124801-18a6f7a8-66fb-11e7-86a9-15554a81a5cf.png)

**Comment by sebas5384** [comment]
Related issue: https://github.com/apollographql/react-apollo/issues/832

**Comment by sebas5384** [comment]
I think it's related to this PR https://github.com/mridgway/hoist-non-react-statics/pull/24/files#diff-168726dbe96b3ce427e7fedce31bb0bcL18

Because it removes properties which they shouldn't be accessed directly in strict mode:
```js
var KNOWN_STATICS = {
  name: true,
  length: true,
  prototype: true,
  caller: true,
  arguments: true,
  arity: true
};
```

**Comment by mridgway** [comment]
I will re-introduce the full known statics list.

**Comment by mridgway** [comment]
Please try v2.1.1.

**Comment by sebas5384** [comment]
Thanks!! I'll notify the React Apollo team :)

**Comment by sebas5384** [comment]
@mridgway all good here! you could close this issue if you want 👍

**Comment by mridgway** [comment]
Great! Thanks for reporting the issue.
