### ISSUE TITLE
Transition TypeScript definition to DefinitelyTyped

### ISSUE THREAD

**Issue by mridgway** [mridgway/hoist-non-react-statics#53]
There has been a lot of churn in the type definitions which I am unable to test since I do not use TypeScript. Since the [guidance from the TypeScript team](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#Publishing) is to use DefinitelyTyped for modules that are not natively written in TypeScript, that is what should be done.

Once a type definition has been published to DefinitelyTyped, I will remove the embedded index.d.ts file.

**Comment by mridgway** [comment]
I will be removing the definitions in the 3.x release regardless of presence of definitions in DefinitelyTyped.

**Comment by mridgway** [comment]
Since these are now removed in master, here are the old definitions for anyone that wants to add these to DefinitelyTyped: https://raw.githubusercontent.com/mridgway/hoist-non-react-statics/cc2234126197f89b9ac33d778899d55b1f089dfa/index.d.ts

**Comment by JounQin** [comment]
@mridgway My PR for declarations has been merged, and [@types/hoist-non-react-statics](https://www.npmjs.com/package/@types/hoist-non-react-statics) has been published.

**Comment by mridgway** [comment]
@JounQin Thank you very much for doing this!

**Comment by hedgepigdaniel** [comment]
Just pointing out that [this](https://github.com/mridgway/hoist-non-react-statics/pull/61) is the cause of https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33690#issuecomment-574065523

Not sure what the right solution is, but it seems like once you've published a package with a `types` field in `package.json`, it will forever (sometimes) take precedence over DefinitelyTyped.
