### ISSUE TITLE
Prop types report missing prop since v3.0.0

### ISSUE THREAD

**Issue by dan-lee** [mridgway/hoist-non-react-statics#57]
Since the latest version I get the misleading warning from PropTypes despite the prop is being provided:

> Warning: Failed prop type: The prop `xxx` is marked as required in `Foo`, but its value is `undefined`.

Compare the same code with different versions in CodeSandbox and check the console:

* v2.5.5: https://codesandbox.io/s/1rn5qj507l
* v3.0.0: https://codesandbox.io/s/olknzl6wlz

Locally I tried to revert this line:

https://github.com/mridgway/hoist-non-react-statics/blob/69090b61794f37a3bf898dd4bc02e0e44d7c8e27/src/index.js#L41

Back to this:

https://github.com/mridgway/hoist-non-react-statics/blob/03a7f2f87ae9d9a41696b2a7f109aa1aab6b9eab/src/index.js#L32

And it seemed to work again. I am not sure what's happening there and I did not investegate further, just wanted to share some insights.

**Comment by mridgway** [comment]
Ah, I see what's happening here. It has to do with how we detect the type of components here: https://github.com/mridgway/hoist-non-react-statics/blob/master/src/index.js#L60. I will follow up on this with a fix.

**Comment by mridgway** [comment]
This should be fixed in v3.0.1.

**Comment by dan-lee** [comment]
Thanks for the quick resolution
