### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by dwqs** [mridgway/hoist-non-react-statics#64]
Hi~~ 

I have a react project and I want to upgrade react-redux from v5.0.7 to v5.1.1, but when I restart my project, I get some error from `hoist-non-react-statics` as follows:

![image](https://user-images.githubusercontent.com/7871813/48328118-861abd80-e67d-11e8-872b-be6645a7fa66.png)

`hoist-non-react-statics` is [a dependency of react-redux](https://github.com/reduxjs/react-redux/blob/v5.1.1/package.json#L48) and I notice that hoist-non-react-statics has changed package.json main field to a cjs file from v2.5.1. The require syntax isn't supported in browser.

Is it a bug for hoist-non-react-statics ???

**Comment by dwqs** [comment]
Anyone can help me?

**Comment by dwqs** [comment]
@mridgway Is it a bug for hoist-non-react-statics ???

**Comment by TrySound** [comment]
@dwqs Nope. The problem is in your build setup. What do you use?
