### ISSUE TITLE
v3 and react peer requirement

### ISSUE THREAD

**Issue by eps1lon** [mridgway/hoist-non-react-statics#65]
I'm opening a separate issue for discoverability starting with my original comment https://github.com/mridgway/hoist-non-react-statics/pull/55#issuecomment-441358612
> @mridgway Why is the peer to react >= 14 required? As far as I understood `react-is` it would just not recognize components from before v14. Since you currently only use `react-is` to detect types that were added in `16.3.0` this shouldn't be an issue.

In addition I Did some more research and the [original PR](facebook/react#12199)  did not mention any version requirement for react. The [RFC](facebook/react#11279)  and the [original commit](https://github.com/facebook/react/commit/41b8c65f1e81ba48192fbb65fd5c742638ef4f82) explicitly say that it has no requirement to react.

This is currently causing trouble with every package that wants to support older and new react versions. Getting all affected to release a new major and drop support for react below 14 just to bump `hoist-non-react-statics` will take time and wouldn't be needed if we could simply backport v3 to a new minor in v2.

Edit:
So I guess you're refering to https://github.com/facebook/react/issues/12882#issuecomment-401944777
> > Which previous versions of react does `react-is` support?
> 
> Should support versions 0.14+
> 
> It relies on `$$typeof` (added in 0.14), so it will not support <= 0.13

But again since `forwardRef` was only added in 16.3 it wouldn't matter in that case. It's only dangerous if you plan on using `isValidElementType` which would return false for components in react <= 0.13

**Comment by mridgway** [comment]
At one point, the code used React directly, but this is not the case anymore. I think you are right that we can remove the peer and require of React.
