### ISSUE TITLE
There should a fail-safe check to prevent non-writable properties from being written

### ISSUE THREAD

**Issue by channikhabra** [mridgway/hoist-non-react-statics#7]
I am getting this error:

```
Uncaught TypeError: Cannot assign to read only property '__reactPatchProxy' of function 'function WrappedComponent() {
            _classCallCheck(this, WrappedComponent);

            return _possibl...<omitted>... }'hoistNonReactStatics @ 
```

:cc @gajus

**Comment by gajus** [comment]
Relevant code, https://github.com/gajus/react-css-modules/blob/v3.7.0/src/extendReactClass.js#L46

**Comment by mridgway** [comment]
That property seems related to https://github.com/gaearon/react-proxy which uses readonly. 

I'd prefer not to do a try/catch here. Is there a way to tell if a property is readonly before trying to modify it?

**Comment by mridgway** [comment]
`Object.getOwnPropertyDescriptor(component, prop).writable` could work.

**Comment by gajus** [comment]
How about instead not writing properties that already exist?

**Comment by mridgway** [comment]
True, that is a good option.

**Comment by gajus** [comment]
> True, that is a good option.

https://github.com/mridgway/hoist-non-react-statics/pull/9

Please merge and release a patch.
