### ISSUE TITLE
missing dist/ folder in 3.3.0 release on GitHub

### ISSUE THREAD

**Issue by jacobsmith** [mridgway/hoist-non-react-statics#75]
Hello,

I'm using some libraries that depend on `hoist-non-react-statics` and from what I can tell, the latest 3.3.0 version on github does not have the `dist/` folder, so the file specified in `package.json # main` cannot be resolved.

The link I used to download was:

https://github.com/mridgway/hoist-non-react-statics/releases/tag/v3.3.0

Additionally, my `yarn` installation pointed to:

https://codeload.github.com/mridgway/hoist-non-react-statics/tar.gz/4fbd062b55ccb657b631505728bc043000ece9a5

I'm not sure if this is an issue with my personal `yarn` installation, issues with libraries that are depending on an incorrect version of this package, or if this library needs to have `npm run build` run before creating the release - I'm still in "investigative" mode, but thought I'd put this up to see if others are having the same issue or if you knew how to resolve.

Thanks!

**Comment by jacobsmith** [comment]
So, I was just able to go into my local yarn cache, find the 3.3.0 version of `hoist-non-react-statics`, and run `npm install` - that triggered the build (and thus, the dist folder was created). I'm not sure if `yarn` just wasn't doing that on install?

`YARN_CACHE_DIR=$(yarn cache dir)`
`cd "$YARN_CACHE_DIR/npm-hoist-non-react-statics-3.3.0/node_modules/hoist-non-react-statics" && npm i`

then in my project,

`rm -rf node_modules`
`yarn install`

that pulled in the cached version of this package that I just ran the `npm i` command (and, therefore, the build). That leads me to believe that `yarn` wasn't running the `install` step of dependencies - I don't know enough about yarn's processes to know if that's consistent with how it normally operates or not.

**Comment by eps1lon** [comment]
The github release tarballs only contain files in version control by default 3.2.0 didn't have the dist/ folder either.

```sh
$ npm view hoist-non-react-statics dist.tarball
https://registry.npmjs.org/hoist-non-react-statics/-/hoist-non-react-statics-3.3.0.tgz
``` 
The linked tarball contains the dist/ folder.

Maybe you use a different registry or proxy to something that includes the source instead of the content published to npm.

**Comment by jacobsmith** [comment]
Hm, okay, thanks for the information. I feel like `yarn`/`npm` issues are difficult to debug :\

I'm going to close this as clearly the issue isn't with this package, but something with my setup must be off. Thanks for the info, @eps1lon!
