### ISSUE TITLE
Use the latest react-is feature "isMemo" but without upgrading to the correct version of react-is

### ISSUE THREAD

**Issue by KevinYaoooooo** [mridgway/hoist-non-react-statics#78]
Use the latest react-is feature "isMemo" but without upgrading to the correct version of react-is

WHY?

**Comment by eps1lon** [comment]
> Use the latest react-is feature "isMemo" but without upgrading to the correct version of react-is
> 
> WHY?

We're not: https://github.com/mridgway/hoist-non-react-statics/blob/4fbd062b55ccb657b631505728bc043000ece9a5/package.json#L27

Do you get the same error as #74?

**Comment by KevinYaoooooo** [comment]
> > Use the latest react-is feature "isMemo" but without upgrading to the correct version of react-is
> > WHY?
> 
> We're not:
> 
> [hoist-non-react-statics/package.json](https://github.com/mridgway/hoist-non-react-statics/blob/4fbd062b55ccb657b631505728bc043000ece9a5/package.json#L27)
> 
> Line 27 in [4fbd062](/mridgway/hoist-non-react-statics/commit/4fbd062b55ccb657b631505728bc043000ece9a5)
> 
>  "react-is": "^16.7.0" 
> Do you get the same error as #74?

Yes, exactly the same error. any solution on this?

**Comment by KevinYaoooooo** [comment]
WHY do you use the "higher" feature without upgrading the dependencies, it would caused a lot of error who using this lib.

**Comment by eps1lon** [comment]
> WHY do you use the "higher" feature without upgrading the dependencies, it would caused a lot of error who using this lib.

I already told you we upgraded the dependency: https://github.com/mridgway/hoist-non-react-statics/pull/73/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L27

The package manager you're using seems to create a broken node_modules/ layout. Maybe your build pipeline is responsible for it.

**Comment by KevinYaoooooo** [comment]
> > WHY do you use the "higher" feature without upgrading the dependencies, it would caused a lot of error who using this lib.
> 
> I already told you we upgraded the dependency: https://github.com/mridgway/hoist-non-react-statics/pull/73/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L27
> 
> The package manager you're using seems to create a broken node_modules/ layout. Maybe your build pipeline is responsible for it.

No~~ **16.7.0** does not have the isMemo function either, it's on  **16.8.1**

see here: https://github.com/CompuIves/codesandbox-client/issues/1521#issuecomment-461975018

**Comment by KevinYaoooooo** [comment]
quote here: 
> So this means that the requested version by hoist-non-react-statics is ^16.6.3, and the resolved version is 16.7.0, which is correct. isMemo got added in 16.8.1.

**Comment by KevinYaoooooo** [comment]
Sorry, my bad, my misunderstanding.

**Comment by manelgarcia** [comment]
Using hoist-non-react-statics with NextJS is also causing this problem for me

`TypeError: ReactIs.isMemo is not a function`

Which is the fix? If isMemo is added in 16.7.0 shouldn't it be working?

Thanks for your time in advance.

**Comment by eps1lon** [comment]
This is likely an issue with the build setup from `NextJS`. `next` requires `react-is@16.6.3` which does not include `isMemo`. It would be solved automatically if `next` wouldn't pint their dependencies to PATCH but rather MAJOR but they [insist on it](https://github.com/zeit/next.js/issues/6465#issuecomment-467813088).

**Comment by DBeardionaire** [comment]
I'm also getting this error from react-redux connect() method after installing on new machine, right now I'm just checking if 
```
If isMemo && If isMemo(component))
```
in the .cjs file locally to get around it for now...  any reason not to put the "react-is" dep to  "16.8.1"?

**Comment by eps1lon** [comment]
@DBeardionaire your build setup is probably broken. Try resolutions field in your package.json to force a single version.

Why we dont bump the version? We dont need to as is shown in the conversation here.
