### ISSUE TITLE
When hoisting: Keep prop value if context value is undefined

### ISSUE THREAD

**Issue by ComLock** [mridgway/hoist-non-react-statics#81]
I'm using script type="module" to load two react components into the browser.
Parent provides a context.
Child consumes a context.

As long as both components come from the same bundle the Child gets the correct context.

However if I load the components from their own bundles. The context is lost.

My workaround for this is to pass in the context as props.
But then the Child cannot be a context Consumer, because it will overwrite the props.

So my question is, if some property exists both as a prop and in the context, which should win?

If the property is undefined in the context it would be nice to keep the prop.

(If anyone has other suggestions on how to make the correct context available to the child, please let me know.)

**Comment by ComLock** [comment]
I used Formik in the Parent. And Formik.connect in the Child.
https://github.com/jaredpalmer/formik/blob/master/src/connect.tsx#L42

**Comment by eps1lon** [comment]
props and context are of no concern in this package. It only handles object properties on the element types. Could you add some code examples so that we're both on the same page about the terminology?

**Comment by ComLock** [comment]
```html
<script type='module'>
    import {Parent} from 'url/Parent.bundle.js';
    import {Child} from 'url/Child.bundle.js';
    //import {Child, Parent} from 'url/Both.bundle.js'; // Works
    ReactDOM.render(
        Parent({
            Child()
        }),
        document.getElementById('reactContainer')
    );
</script>
```

Parent.mjs
```js
import {Formik} from 'formik';


export const MyComponent = ({
	children,
	initialValues
}) => {
	return <Formik
		initialValues={initialValues}
		render={(formik) => {
			return <div formik={formik}>{children}</div>;
		}}
	/>
}
```

Child.mjs
```js
import {connect} from 'formik';


const Component = ({formik}) => {
	console.debug(formik);
	return <p>Connected</p>;
};

export const ConnectedComponent = connect(Component);

```

Both.mjs
```
export {Parent} from './Parent.mjs';
export {Child} from './Child.mjs';
`
``

**Comment by ComLock** [comment]
I both instances the React "Dom" is the same, but the formik prop on the Child is different.

![Skjermbilde 2019-05-09 kl  13 21 08](https://user-images.githubusercontent.com/118847/57449930-714e6980-725d-11e9-8ae3-078551e89e30.png)

![Skjermbilde 2019-05-09 kl  13 21 42](https://user-images.githubusercontent.com/118847/57449935-73b0c380-725d-11e9-8b07-8905346ed90c.png)

**Comment by eps1lon** [comment]
This doesn't seem like hoist-non-react-statics has anything to do with it.

```js
ReactDOM.render(
        Parent({
            Child()
        }),
        document.getElementById('reactContainer')
    );
```
is not valid in react as well. Either use jsx or React.createElement.

**Comment by ComLock** [comment]
If you console.debug(Parent); You will find that's it's a function that does React.createElement.

**Comment by ComLock** [comment]
So wrapping with React.createElement changes nothing.

Since React itself does not recommend using a context unless inside a lib, I think passing around what I need, is the way to go.
