### ISSUE TITLE
Incorrect AMD definition

### ISSUE THREAD

**Issue by staceysern** [mridgway/hoist-non-react-statics#89]
The AMD definition does not declare the dependency on react-is and uses the global require, not the AMD local require.

Two possible ways of handling this would be a correct AMD definition here would be either

`define(["react-is"], function(ReactIs) {...});`

or
    
`define(["require", "react-is"], function(require) { var ReactIs = require("react-is"); ...});`

**Comment by TrySound** [comment]
The fix is in master

**Comment by mridgway** [comment]
Fix is published in v3.3.1
